import { auth, db } from './firebase-config.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { ref, onValue, set, update, query, orderByChild, limitToLast, serverTimestamp, onDisconnect, get } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js';

const $ = id => document.getElementById(id); const root = document.documentElement;
let historyRecords = [], historyLimit = Number(localStorage.getItem('iot-history-limit') || 50), selectedMetric = 'temperature', chart, current = { temperature:null, humidity:null, ldr:null, bulb:false, mode:'manual', timestamp:null }, settings = { ldrThreshold:500, ldrInverted:false };
const fmtTime = ts => ts ? new Date(Number(ts)).toLocaleString([], {day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '—';
const toast = (message,type='success') => { const el=document.createElement('div'); el.className=`toast ${type}`; el.textContent=message; $('toast-container').appendChild(el); setTimeout(()=>el.remove(),3200); };
const setFirebaseStatus = (ok,msg) => { $('firebase-status').textContent=msg; $('connection-text').textContent=`Firebase: ${msg}`; $('settings-connection').textContent=ok?'Realtime Database connection is active.':'Realtime Database connection is unavailable.'; $('live-label').textContent=ok?'Live data connected':'Connection Lost'; $('firebase-dot').classList.toggle('online',ok); $('settings-status').innerHTML=`<span class="status-dot ${ok?'online':''}"></span>${msg}`; };
const setText=(id,v)=>{const e=$(id);if(e)e.textContent=v;};
function renderCurrent(){ const c=current; setText('temperature',c.temperature == null?'—':`${Number(c.temperature).toFixed(1)}°`); setText('humidity',c.humidity == null?'—':`${Number(c.humidity).toFixed(0)}%`); setText('ldr',c.ldr==null?'—':Math.round(Number(c.ldr))); setText('bulb-status',c.bulb?'ON':'OFF'); setText('last-updated',`Last updated ${fmtTime(c.timestamp)}`); setText('live-temp',c.temperature==null?'—':`${Number(c.temperature).toFixed(1)} °C`); setText('live-hum',c.humidity==null?'—':`${Number(c.humidity).toFixed(0)} %`); setText('live-ldr',c.ldr==null?'—':Math.round(Number(c.ldr))); setText('live-bulb',c.bulb?'ON':'OFF'); setText('live-mode',String(c.mode||'manual').toUpperCase()); setText('live-time',fmtTime(c.timestamp)); setText('control-status',c.bulb?'ON':'OFF'); setText('control-mode',String(c.mode).toUpperCase()); setText('auto-mode',String(c.mode).toUpperCase()); setText('auto-ldr',c.ldr==null?'—':Math.round(Number(c.ldr))); setText('auto-threshold',settings.ldrThreshold); setText('auto-logic',settings.ldrInverted?'LDR > Threshold':'LDR < Threshold'); setText('auto-bulb',c.bulb?'ON':'OFF'); document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===c.mode)); $('mode-chip').textContent=String(c.mode).toUpperCase(); $('bulb-dot').classList.toggle('online',c.bulb); $('bulb-visual').classList.toggle('on',c.bulb); $('bulb-toggle').textContent=c.bulb?'TURN OFF':'TURN ON';
  const dark = c.ldr != null && (settings.ldrInverted ? Number(c.ldr)>settings.ldrThreshold : Number(c.ldr)<settings.ldrThreshold); const decision = c.mode==='automatic' ? (dark?'DARK — BULB ON':'BRIGHT — BULB OFF') : 'Manual control active'; setText('decision',decision); setText('decision-detail',c.mode==='automatic'?`LDR ${Math.round(Number(c.ldr))} vs threshold ${settings.ldrThreshold}. ${settings.ldrInverted?'Higher':'Lower'} values indicate darkness.`:'Switch to automatic mode to let the ESP32 evaluate the LDR threshold.'); setText('auto-decision',c.mode==='automatic'?decision:'Waiting for automatic mode'); }
function loadHistory(){ const q=query(ref(db,'iot/history'),orderByChild('timestamp'),limitToLast(historyLimit)); $('history-loading').hidden=false; $('history-empty').hidden=true; $('history-error').hidden=true; onValue(q,snap=>{historyRecords=[];snap.forEach(child=>historyRecords.push({id:child.key,...child.val()}));historyRecords.reverse();renderHistory();renderChart();$('history-loading').hidden=true;},err=>{$('history-loading').hidden=true;$('history-error').hidden=false;toast('Unable to load sensor history.','error');console.error(err);}); }
function renderHistory(){ const body=$('history-body');body.innerHTML=''; setText('history-summary',`${historyRecords.length} record${historyRecords.length===1?'':'s'} loaded · latest first`); if(!historyRecords.length){$('history-empty').hidden=false;return;} historyRecords.forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${fmtTime(r.timestamp)}</td><td>${r.temperature==null?'—':Number(r.temperature).toFixed(1)} °C</td><td>${r.humidity==null?'—':Number(r.humidity).toFixed(0)} %</td><td>${r.ldr==null?'—':Math.round(Number(r.ldr))}</td><td><span class="table-status ${r.bulb?'on':''}">${r.bulb?'ON':'OFF'}</span></td><td>${String(r.mode||'manual').toUpperCase()}</td>`;body.appendChild(tr);}); }
function renderChart(){ const canvas=$('sensor-chart'); if(!window.Chart)return; const rows=[...historyRecords].reverse(); const labels=rows.map(r=>new Date(Number(r.timestamp)).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})); const data=rows.map(r=>Number(r[selectedMetric]??0)); if(chart)chart.destroy(); chart=new Chart(canvas,{type:'line',data:{labels,datasets:[{label:selectedMetric==='ldr'?'LDR':selectedMetric[0].toUpperCase()+selectedMetric.slice(1),data,borderWidth:2,pointRadius:2,tension:.35,fill:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:false,grid:{color:'rgba(128,128,128,.15)'}}}}}); }
function saveControl(patch,msg){return update(ref(db,'iot/control'),patch).then(()=>toast(msg));}
function init(){ root.dataset.theme=localStorage.getItem('iot-theme')||'dark'; $('history-limit').value=historyLimit; $('chart-limit').value=historyLimit; const storedTheme=()=>{const n=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=n;localStorage.setItem('iot-theme',n);}; $('theme-toggle').onclick=storedTheme; $('settings-theme').onclick=storedTheme; $('logout-btn').onclick=async()=>{try{await signOut(auth);location.replace('login.html');}catch(e){toast('Logout failed.','error')}};
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>saveControl({mode:b.dataset.mode},`Mode changed to ${b.dataset.mode.toUpperCase()}`)); $('bulb-toggle').onclick=()=>saveControl({bulb:!current.bulb},`Bulb turned ${current.bulb?'OFF':'ON'}`); $('save-threshold').onclick=async()=>{const v=Number($('threshold-input').value);if(!Number.isInteger(v)||v<0||v>4095)return toast('Threshold must be an integer from 0 to 4095.','error');const inv=document.querySelector('input[name="ldr-logic"]:checked').value==='true';try{await set(ref(db,'iot/settings'),{ldrThreshold:v,ldrInverted:inv});toast('Threshold saved.');}catch(e){toast('Could not save threshold.','error')}};
  document.querySelectorAll('input[name="ldr-logic"]').forEach(r=>r.onchange=()=>{const v=Number($('threshold-input').value);if(Number.isInteger(v)&&v>=0&&v<=4095)set(ref(db,'iot/settings'),{ldrThreshold:v,ldrInverted:r.value==='true'}).then(()=>toast('Darkness logic updated.')).catch(()=>toast('Could not save logic.','error'));});
  const reloadHistory=()=>{historyLimit=Number($('history-limit').value);localStorage.setItem('iot-history-limit',historyLimit);$('chart-limit').value=historyLimit;loadHistory();}; $('history-limit').onchange=reloadHistory; $('chart-limit').onchange=()=>{$('history-limit').value=$('chart-limit').value;reloadHistory();}; document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{selectedMetric=b.dataset.metric;document.querySelectorAll('[data-metric]').forEach(x=>x.classList.toggle('active',x===b));renderChart();});
  $('download-csv').onclick=()=>{if(!historyRecords.length)return toast('No history available to export.','error');const rows=[['Timestamp','Temperature','Humidity','LDR','Bulb','Mode'],...historyRecords.map(r=>[new Date(Number(r.timestamp)).toISOString(),r.temperature??'',r.humidity??'',r.ldr??'',r.bulb?'ON':'OFF',String(r.mode||'manual').toUpperCase()])];const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='iot-sensor-history.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV downloaded.');};
  document.querySelectorAll('[data-section-link]').forEach(a=>a.onclick=()=>{document.querySelectorAll('[data-section-link]').forEach(x=>x.classList.remove('active'));a.classList.add('active');setText('page-title',a.textContent.trim());}); $('mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
  onAuthStateChanged(auth,user=>{if(!user){location.replace('login.html');return;} $('app').hidden=false;$('app-loading').remove();setText('user-email',user.email||'Authenticated user'); attachFirebase();}); }
function attachFirebase(){ const conn=ref(db,'.info/connected'); onValue(conn,s=>setFirebaseStatus(s.val()===true,s.val()===true?'Connected':'Connection Lost')); onValue(ref(db,'iot/current'),s=>{const v=s.val()||{};current={...current,...v};renderCurrent();},e=>{setFirebaseStatus(false,'Connection Lost');toast('Firebase data unavailable.','error');}); onValue(ref(db,'iot/settings'),s=>{const v=s.val()||{};settings={ldrThreshold:Number(v.ldrThreshold??500),ldrInverted:Boolean(v.ldrInverted??false)};$('threshold-input').value=settings.ldrThreshold;document.querySelector(`input[name="ldr-logic"][value="${settings.ldrInverted}"]`).checked=true;renderCurrent();}); loadHistory(); }
init();
